name: mlops-control
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi==0.109.0
      - uvicorn[standard]==0.27.0
      - sqlalchemy==2.0.25
      - pydantic==2.5.3
      - pydantic-settings==2.1.0
      - paramiko==3.4.0
      - gitpython==3.1.41
      - pyyaml==6.0.1
      - jinja2==3.1.3
      - python-multipart==0.0.6
      - aiosqlite==0.19.0
      - apscheduler==3.10.4
